### ISSUE TITLE
Problem with Scopus files

### ISSUE THREAD

**Issue by phillipeG-ucen** [massimoaria/bibliometrix#285]
with files downloaded directly from SCOPUS, following the indications of bibliometrix, I have problems with some analyses. 

Intellectual structure -> Thematic evolution  -> ERROR: Column `TI` not found in `.data`.
Overview -> Main Information  ->ERROR: non-character argument

so on. 
The files have been downloaded directly from scopus. I have tried with CSV and bibtext with the same errors. 
Any advice please?

**Comment by massimoaria** [comment]
The error is because when you downloaded the collection you did not select the entire metadata set.
The default selection proposed by Scopus is limited to only a limited set of metadata.
To download the full set of information follow the two steps outlined in the attached pdf file.
[Scopus export steps.pdf](https://github.com/massimoaria/bibliometrix/files/10376802/Scopus.export.steps.pdf)

**Comment by phillipeG-ucen** [comment]
Hello
Thank you for your reply. However, I have made sure to select all the
metadata. But the error persists.
Could it be that I am using the new version of Scopus to be able to
download more than 2000 references?

**Comment by massimoaria** [comment]
'Could it be that I am using the new version of Scopus to be able to
download more than 2000 references?'

Yes, This is the problem.
Scopus makes available a "fast download" procedure to overcome the limit of 2000 items but in this case, the user can only download a few metadata. 
e.g. the error you are facing with bibliometrix "ERROR: Column TI not found in .data." means that your collection does not contain publication titles! (TI is the Tag for title column)

**Comment by massimoaria** [comment]
The issue has been solved in bibliometrix 4.1.
Now, it can import and convert also new Scopus BibTex and CSV formats.

**Comment by phillipeG-ucen** [comment]
Thank you.
But the problem remains.
I have re-downloaded the data from Scopus, making sure to download all the
metadata.
It still does not identify the titles, so I cannot perform the analyses
that need them.
Attached is the CSV
 scopus praxis new.csv
<https://drive.google.com/file/d/11R74ZiwBZcCpy8nDAiyb8obB2ltR3oqk/view?usp=drive_web>
