### ISSUE TITLE
Error under "coupling" after applying a filter

### ISSUE THREAD

**Issue by BTunca** [massimoaria/bibliometrix#293]
Hi,
We are conducting some coupling analyses under "Clustering with coupling" based on "Documents", coupling measured by "references". When we upload our plain text WOS data and run the analyses, we get the results, but the moment we apply a year filter we get an "Error: Not a graph object".

Nonetheless, even after applying the filter, we can run the analyses with "Authors" or "Sources" as the unit of analyses. Also with "documents" other coupling measures like abstracts would work.- The error appears only for documents measured by references.

This is the error log in RStudio:

Network matrix is empty!
The analysis cannot be performed

Warning: Error in V: Not a graph object
  150: stop
  149: V
  148: couplingMap
  147: eventReactiveValueFunc [/Library/Frameworks/R.framework/Versions/4.2/Resources/library/bibliometrix/biblioshiny/server.R#3717]
  103: CMMAP
  102: renderPlotly [/Library/Frameworks/R.framework/Versions/4.2/Resources/library/bibliometrix/biblioshiny/server.R#3733]
  101: func
   98: shinyRenderWidget
   97: func
   84: renderFunc
   83: output$CMPlot
    2: runApp
    1: biblioshiny

We appreciate any recommendation,

Regards,
Burak

**Comment by massimoaria** [comment]
The issue should be resolved in the last update (4.1.1). Please check it.

**Comment by evrimyanar** [comment]
Unfortunately, I still get the same error after updating the package.

**Comment by massimoaria** [comment]
Please upload your dataset so I can try to solve the issue.

**Comment by evrimyanar** [comment]
Thank you very much! It is in wos format.

[BLA2023cleandata31Jan.txt](https://github.com/massimoaria/bibliometrix/files/10730721/BLA2023cleandata31Jan.txt)

**Comment by massimoaria** [comment]
I have just solved the issue. Please try to update bibliometrix from github

**Comment by BTunca** [comment]
> I have just solved the issue. Please try to update bibliometrix from github

Thanks a lot Massimo, it is working!
